import {Platform, StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F3EA',
  },
  container: {
    flexGrow: 1,
    padding: 20,
    paddingBottom: 36,
  },
  header: {
    marginBottom: 18,
    paddingTop: 24,
  },
  eyebrow: {
    color: '#49624A',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.2,
    marginBottom: 8,
  },
  title: {
    color: '#23251F',
    fontSize: 34,
    fontWeight: '800',
    letterSpacing: 0,
    marginBottom: 8,
  },
  description: {
    color: '#676B5E',
    fontSize: 16,
    lineHeight: 23,
  },
  screenStack: {
    gap: 14,
  },
  mapHome: {
    backgroundColor: '#F5F3EA',
    flex: 1,
  },
  tabScreen: {
    backgroundColor: '#F5F3EA',
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'ios' ? 58 : 28,
    paddingBottom: Platform.OS === 'ios' ? 104 : 92,
  },
  tabScreenHeader: {
    marginBottom: 14,
  },
  tabScreenTitle: {
    color: '#23251F',
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: 0,
    marginBottom: 12,
  },
  mapTopPanel: {
    left: 16,
    position: 'absolute',
    right: 16,
    top: Platform.OS === 'ios' ? 58 : 28,
  },
  mapBrandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  mapEyebrow: {
    color: '#49624A',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  mapTitle: {
    color: '#23251F',
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: 0,
  },
  mapSearchBar: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.96)',
    borderColor: '#E4E0D5',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    padding: 8,
    shadowColor: '#3B3528',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.12,
    shadowRadius: 24,
  },
  mapSearchInput: {
    color: '#23251F',
    flex: 1,
    fontSize: 16,
    minHeight: 42,
    paddingHorizontal: 10,
  },
  mapLocationButton: {
    alignItems: 'center',
    backgroundColor: '#EEF4EA',
    borderColor: '#B8C8B6',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 10,
  },
  mapLocationButtonActive: {
    backgroundColor: '#49624A',
    borderColor: '#49624A',
  },
  mapLocationButtonText: {
    color: '#49624A',
    fontSize: 13,
    fontWeight: '900',
  },
  mapLocationButtonActiveText: {
    color: '#FFFFFF',
  },
  mapSearchButton: {
    alignItems: 'center',
    backgroundColor: '#23251F',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 16,
  },
  mapSearchButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  mapStatus: {
    alignItems: 'center',
    backgroundColor: 'rgba(236, 231, 217, 0.94)',
    borderColor: '#DDD6C4',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  mapStatusText: {
    color: '#3F4438',
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
  },
  bottomSheet: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E0D5',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderWidth: 1,
    bottom: 0,
    left: 0,
    padding: 16,
    paddingBottom: Platform.OS === 'ios' ? 26 : 18,
    position: 'absolute',
    right: 0,
    shadowColor: '#3B3528',
    shadowOffset: {width: 0, height: -10},
    shadowOpacity: 0.12,
    shadowRadius: 26,
  },
  bottomSheetAboveTabs: {
    bottom: Platform.OS === 'ios' ? 88 : 76,
  },
  bottomTabBar: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E0D5',
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: 'row',
    gap: 8,
    left: 0,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'ios' ? 28 : 14,
    position: 'absolute',
    right: 0,
    shadowColor: '#3B3528',
    shadowOffset: {width: 0, height: -8},
    shadowOpacity: 0.08,
    shadowRadius: 18,
  },
  bottomTabButton: {
    alignItems: 'center',
    borderRadius: 8,
    flex: 1,
    gap: 6,
    justifyContent: 'center',
    minHeight: 48,
    paddingVertical: 8,
  },
  bottomTabButtonActive: {
    backgroundColor: '#EEF4EC',
  },
  bottomTabIndicator: {
    backgroundColor: 'transparent',
    borderRadius: 2,
    height: 3,
    width: 24,
  },
  bottomTabIndicatorActive: {
    backgroundColor: '#49624A',
  },
  bottomTabButtonText: {
    color: '#676B5E',
    fontSize: 13,
    fontWeight: '800',
  },
  bottomTabButtonTextActive: {
    color: '#23251F',
  },
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: '#D8D2C2',
    borderRadius: 2,
    height: 4,
    marginBottom: 14,
    width: 42,
  },
  sheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sheetTitle: {
    color: '#23251F',
    fontSize: 20,
    fontWeight: '900',
  },
  sheetCount: {
    color: '#49624A',
    fontSize: 13,
    fontWeight: '800',
  },
  sheetScroll: {
    maxHeight: 260,
  },
  sheetList: {
    gap: 10,
    paddingBottom: 4,
  },
  listFilterInput: {
    marginBottom: 12,
  },
  sheetRestaurant: {
    alignItems: 'center',
    backgroundColor: '#FCFBF7',
    borderColor: '#E4E0D5',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 12,
  },
  communityPost: {
    alignItems: 'center',
    backgroundColor: '#FCFBF7',
    borderColor: '#E4E0D5',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 12,
  },
  communityWriteScroll: {
    maxHeight: '100%',
  },
  communityWriteContent: {
    paddingBottom: 36,
  },
  inlineSearchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  inlineSearchInput: {
    flex: 1,
  },
  inlineSearchButton: {
    alignItems: 'center',
    backgroundColor: '#23251F',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  inlineSearchButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  selectedPlaceBox: {
    backgroundColor: '#EEF4EC',
    borderColor: '#C8D7C3',
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    marginBottom: 14,
    padding: 12,
  },
  savedPlaceSection: {
    marginBottom: 14,
  },
  savedPlaceTitle: {
    color: '#505449',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 8,
  },
  savedPlaceList: {
    gap: 10,
  },
  savedPlaceScroll: {
    maxHeight: 260,
  },
  savedPlaceEmpty: {
    color: '#777B6E',
    fontSize: 13,
    lineHeight: 19,
  },
  friendSection: {
    marginBottom: 18,
  },
  friendRow: {
    alignItems: 'center',
    backgroundColor: '#FCFBF7',
    borderColor: '#E4E0D5',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 12,
  },
  friendActionRow: {
    gap: 8,
  },
  friendRestaurantRow: {
    alignItems: 'center',
    backgroundColor: '#FCFBF7',
    borderColor: '#E4E0D5',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 12,
  },
  smallActionButton: {
    alignItems: 'center',
    borderColor: '#49624A',
    borderRadius: 8,
    borderWidth: 1,
    minWidth: 52,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  smallActionButtonText: {
    color: '#49624A',
    fontSize: 12,
    fontWeight: '900',
  },
  smallActionDangerButton: {
    borderColor: '#D9A09A',
  },
  smallActionDangerButtonText: {
    color: '#B42318',
  },
  placeResultList: {
    gap: 10,
    marginBottom: 14,
  },
  placeResultItem: {
    alignItems: 'center',
    backgroundColor: '#FCFBF7',
    borderColor: '#E4E0D5',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 10,
  },
  placeResultItemActive: {
    borderColor: '#49624A',
  },
  placeSelectText: {
    color: '#49624A',
    fontSize: 12,
    fontWeight: '900',
  },
  writeButton: {
    alignItems: 'center',
    backgroundColor: '#49624A',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 14,
  },
  writeButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  sheetSaveButton: {
    alignItems: 'center',
    borderColor: '#C9C2B0',
    borderRadius: 8,
    borderWidth: 1,
    minWidth: 68,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  sheetSaveButtonActive: {
    backgroundColor: '#49624A',
    borderColor: '#49624A',
  },
  sheetSaveButtonText: {
    color: '#49624A',
    fontSize: 12,
    fontWeight: '900',
  },
  sheetSaveButtonActiveText: {
    color: '#FFFFFF',
  },
  sheetEmptyText: {
    color: '#777B6E',
    fontSize: 14,
    lineHeight: 20,
    paddingVertical: 22,
    textAlign: 'center',
  },
  detailTopRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  closeButton: {
    borderColor: '#C9C2B0',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  closeButtonText: {
    color: '#505449',
    fontSize: 12,
    fontWeight: '900',
  },
  accountActionGrid: {
    gap: 10,
    marginTop: 4,
  },
  accountSecondaryRow: {
    flexDirection: 'row',
    gap: 10,
  },
  accountSecondaryButton: {
    alignItems: 'center',
    borderColor: '#C9C2B0',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  accountSecondaryButtonText: {
    color: '#49624A',
    fontSize: 14,
    fontWeight: '900',
  },
  accountDangerButton: {
    alignItems: 'center',
    borderColor: '#D9A09A',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  accountDangerButtonText: {
    color: '#B42318',
    fontSize: 14,
    fontWeight: '900',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E0D5',
    borderRadius: 8,
    borderWidth: 1,
    padding: 18,
    shadowColor: '#3B3528',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.06,
    shadowRadius: 18,
  },
  sectionTitle: {
    color: '#23251F',
    fontSize: 19,
    fontWeight: '800',
    marginBottom: 14,
  },
  field: {
    gap: 7,
    marginBottom: 14,
  },
  label: {
    color: '#505449',
    fontSize: 13,
    fontWeight: '700',
  },
  input: {
    backgroundColor: '#FCFBF7',
    borderColor: '#D8D2C2',
    borderRadius: 8,
    borderWidth: 1,
    color: '#23251F',
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  contentInput: {
    minHeight: 96,
    textAlignVertical: 'top',
  },
  segmentedControl: {
    backgroundColor: '#F1EDE2',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 6,
    marginBottom: 18,
    padding: 4,
  },
  tabButton: {
    alignItems: 'center',
    borderRadius: 7,
    flex: 1,
    paddingVertical: 11,
  },
  tabButtonActive: {
    backgroundColor: '#FFFFFF',
  },
  tabButtonText: {
    color: '#676B5E',
    fontSize: 15,
    fontWeight: '700',
  },
  tabButtonTextActive: {
    color: '#23251F',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#49624A',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  secondaryButton: {
    alignItems: 'center',
    borderColor: '#C9C2B0',
    borderRadius: 8,
    borderWidth: 1,
    minWidth: 74,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  secondaryButtonActive: {
    backgroundColor: '#49624A',
    borderColor: '#49624A',
  },
  secondaryButtonText: {
    color: '#49624A',
    fontSize: 13,
    fontWeight: '800',
  },
  secondaryButtonActiveText: {
    color: '#FFFFFF',
  },
  secondaryAction: {
    alignItems: 'center',
    borderColor: '#C9C2B0',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  secondaryActionDanger: {
    borderColor: '#D9A09A',
  },
  secondaryActionText: {
    color: '#49624A',
    fontSize: 14,
    fontWeight: '800',
  },
  secondaryActionDangerText: {
    color: '#B42318',
  },
  actionRow: {
    gap: 10,
  },
  searchRow: {
    flexDirection: 'row',
    gap: 10,
  },
  searchInput: {
    flex: 1,
  },
  searchButton: {
    alignItems: 'center',
    backgroundColor: '#23251F',
    borderRadius: 8,
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  searchButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  messageBox: {
    alignItems: 'center',
    backgroundColor: '#ECE7D9',
    borderColor: '#DDD6C4',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
    padding: 13,
  },
  messageError: {
    backgroundColor: '#FEF3F2',
    borderColor: '#F5C5C0',
  },
  messageSuccess: {
    backgroundColor: '#EEF4EC',
    borderColor: '#C8D7C3',
  },
  messageText: {
    color: '#3F4438',
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  mapCard: {
    backgroundColor: '#DDE7D7',
    bottom: 0,
    left: 0,
    overflow: 'hidden',
    position: 'absolute',
    right: 0,
    top: 0,
  },
  mapHeader: {
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  mapHint: {
    color: '#777B6E',
    fontSize: 13,
    marginBottom: 14,
  },
  mapCanvas: {
    alignItems: 'center',
    backgroundColor: '#DDE7D7',
    flex: 1,
    justifyContent: 'center',
    position: 'relative',
  },
  mapWebView: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  mapWebViewContent: {
    flex: 1,
  },
  listStack: {
    gap: 10,
  },
  restaurantItem: {
    alignItems: 'center',
    backgroundColor: '#FCFBF7',
    borderColor: '#E4E0D5',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 13,
  },
  restaurantItemActive: {
    borderColor: '#49624A',
  },
  restaurantTextGroup: {
    flex: 1,
    gap: 4,
  },
  restaurantName: {
    color: '#23251F',
    fontSize: 16,
    fontWeight: '800',
  },
  restaurantMeta: {
    color: '#49624A',
    fontSize: 13,
    fontWeight: '700',
  },
  restaurantAddress: {
    color: '#676B5E',
    fontSize: 13,
    lineHeight: 18,
  },
  postDate: {
    color: '#8A877C',
    fontSize: 12,
    fontWeight: '700',
  },
  detailName: {
    color: '#23251F',
    fontSize: 22,
    fontWeight: '900',
    marginBottom: 10,
  },
  detailLine: {
    color: '#505449',
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 6,
  },
  memoBox: {
    gap: 8,
    marginBottom: 12,
    marginTop: 10,
  },
  memoInput: {
    minHeight: 72,
    textAlignVertical: 'top',
  },
  postContent: {
    color: '#3F4438',
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 14,
  },
  postImage: {
    backgroundColor: '#EEF4EC',
    borderRadius: 8,
    height: 180,
    marginBottom: 14,
    width: '100%',
  },
  postRestaurantBox: {
    backgroundColor: '#FCFBF7',
    borderColor: '#E4E0D5',
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    marginBottom: 12,
    padding: 12,
  },
  postActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  recommendButton: {
    alignItems: 'center',
    borderColor: '#C9C2B0',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 12,
  },
  recommendButtonActive: {
    backgroundColor: '#49624A',
    borderColor: '#49624A',
  },
  recommendButtonText: {
    color: '#49624A',
    fontSize: 14,
    fontWeight: '900',
  },
  recommendButtonActiveText: {
    color: '#FFFFFF',
  },
  commentSection: {
    borderTopColor: '#E4E0D5',
    borderTopWidth: 1,
    paddingTop: 14,
  },
  commentList: {
    gap: 10,
    marginBottom: 12,
  },
  commentItem: {
    backgroundColor: '#FCFBF7',
    borderColor: '#E4E0D5',
    borderRadius: 8,
    borderWidth: 1,
    gap: 5,
    padding: 10,
  },
  commentContent: {
    color: '#3F4438',
    fontSize: 14,
    lineHeight: 20,
  },
  commentInputRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  commentInput: {
    flex: 1,
  },
  editBox: {
    backgroundColor: '#FCFBF7',
    borderColor: '#E4E0D5',
    borderRadius: 8,
    borderWidth: 1,
    marginBottom: 14,
    padding: 12,
  },
  editActionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  editPrimaryButton: {
    flex: 1,
  },
  commentEditBox: {
    gap: 8,
  },
  commentEditInput: {
    minHeight: 72,
    textAlignVertical: 'top',
  },
  accountText: {
    color: '#505449',
    fontSize: 15,
    marginBottom: 16,
  },
  emptyText: {
    color: '#777B6E',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  pressed: {
    opacity: 0.76,
    transform: [{scale: 0.99}],
  },
  disabled: {
    opacity: 0.5,
  },
});
